// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SmartCitySecurity.Data.Contexts;

#nullable disable

namespace SmartCitySecurity.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartCitySecurity.Models.Habitante", b =>
                {
                    b.Property<int>("HabitanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitanteId"));

                    b.Property<int>("Cpf")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EnderecoHabitante")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("HabitanteNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("HistoricoCriminal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("Telefone")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("HabitanteId");

                    b.HasIndex("HabitanteId");

                    b.HasIndex("EnderecoHabitante", "Cpf")
                        .HasDatabaseName("IDX_ENDERECO_CPF");

                    b.ToTable("HABITANTE", (string)null);
                });

            modelBuilder.Entity("SmartCitySecurity.Models.ModeloCrime", b =>
                {
                    b.Property<int>("CrimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrimeId"));

                    b.Property<string>("ArmaUtilizada")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Gravidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeCrime")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("StatusCrime")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoCrime")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("CrimeId");

                    b.HasIndex("CrimeId");

                    b.HasIndex("NomeCrime", "TipoCrime")
                        .HasDatabaseName("IDX_NOME_TIPO");

                    b.ToTable("CRIME", (string)null);
                });

            modelBuilder.Entity("SmartCitySecurity.Models.ModeloEmergencia", b =>
                {
                    b.Property<int>("EmergenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergenciaId"));

                    b.Property<DateTime>("DataEmergencia")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("HabitanteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LocalEmergencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("SistemaVigilanciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusEmergencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoEmergencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("EmergenciaId");

                    b.HasIndex("EmergenciaId");

                    b.HasIndex("HabitanteId");

                    b.HasIndex("SistemaVigilanciaId");

                    b.HasIndex("TipoEmergencia", "DataEmergencia")
                        .HasDatabaseName("IDX_TIPO_DATA");

                    b.ToTable("EMERGENCIA", (string)null);
                });

            modelBuilder.Entity("SmartCitySecurity.Models.ModeloSistemaVigilancia", b =>
                {
                    b.Property<int>("SistemaVigilanciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SistemaVigilanciaId"));

                    b.Property<DateTime>("DataVideo")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("Instalacao")
                        .HasColumnType("date");

                    b.Property<string>("RegistroIncidentes")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ResolucaVideo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ResponsavelManutencao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SistemaLocalizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("SistemaNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UltimaManutencao")
                        .HasColumnType("date");

                    b.HasKey("SistemaVigilanciaId");

                    b.HasIndex("SistemaVigilanciaId");

                    b.HasIndex("SistemaNome", "SistemaLocalizacao")
                        .HasDatabaseName("IDX_NOME_LOCAL");

                    b.ToTable("SISTEMA_VIGILANCIA", (string)null);
                });

            modelBuilder.Entity("SmartCitySecurity.Models.RecursosPoliciais", b =>
                {
                    b.Property<int>("RecursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecursoId"));

                    b.Property<DateTime>("Aquisicao")
                        .HasColumnType("date");

                    b.Property<int>("Capacidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Delegacias")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Disponibilidade")
                        .HasColumnType("BOOLEAN");

                    b.Property<int>("EmergenciaID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LocalizacaoRecurso")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeAgentes")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ReponsavelManutencao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoRecurso")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UltimaManutencao")
                        .HasColumnType("date");

                    b.HasKey("RecursoId");

                    b.HasIndex("EmergenciaID");

                    b.HasIndex("RecursoId");

                    b.HasIndex("Recurso", "Disponibilidade")
                        .HasDatabaseName("IDX_RECURSO_DISPONIBILIDADE");

                    b.ToTable("RECURSOS_POLICIAIS", (string)null);
                });

            modelBuilder.Entity("SmartCitySecurity.Models.ModeloEmergencia", b =>
                {
                    b.HasOne("SmartCitySecurity.Models.Habitante", "Habitante")
                        .WithMany()
                        .HasForeignKey("HabitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCitySecurity.Models.ModeloSistemaVigilancia", "SistemaVigilancia")
                        .WithMany()
                        .HasForeignKey("SistemaVigilanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitante");

                    b.Navigation("SistemaVigilancia");
                });

            modelBuilder.Entity("SmartCitySecurity.Models.RecursosPoliciais", b =>
                {
                    b.HasOne("SmartCitySecurity.Models.ModeloEmergencia", "Emergencia")
                        .WithMany()
                        .HasForeignKey("EmergenciaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emergencia");
                });
#pragma warning restore 612, 618
        }
    }
}
